### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by DeadFishw** [cruzdb/cruzdb#75]
When I try to make the whole program, I get an error that google/protobuf/port_def.inc cannot be found. Is there anyway to solve this problem? I am using WSL ubuntu and I had my protobuf and cruzdb installed at different folders.

**Comment by dotnwat** [comment]
I haven't tried to build this on WSL. Linux and Mac were used.

it might be because the version of protobuf installed in WSL is not what cruzdb expects. in this file https://github.com/cruzdb/cruzdb/blob/master/.travis.yml there are the version of the OS distributions that we were building and testing on. you could use those versions to look up which version of protobuf-dev was being used.

**Comment by DeadFishw** [comment]
I think WSL and Linux acts the same way. I think the problem may be that I have not added some of the environment variable.
